### ISSUE TITLE
Cannot read property 'runOutsideAngular' of undefined

### ISSUE THREAD

**Issue by GabriMagic** [vrn-dev/ng6-socket-io#3]
Hello, I'm trying to use this with my Angular 6, I have the app.module config:

```
SocketIoModule.forRoot(config)
```

And simple chat service:

```
import { Injectable } from '@angular/core';
import { Socket } from 'ng6-socket-io';
import { map } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class ChatService {

  constructor(private socket: Socket) {
    console.log('Init ChatService');
  }

  sendMessage(msg: string) {
    this.socket.emit('message', msg);
  }

  getMessage() {
    return this.socket.fromEvent('message').pipe(map(data => data));
  }
}
```

And when I go to the web, I get this in the console:

![image](https://user-images.githubusercontent.com/6409499/47052344-c599db00-d19f-11e8-9e21-8b0310ac286d.png)

**Comment by christian-quisbert** [comment]
i have the same problem..

**Comment by GabriMagic** [comment]
https://www.npmjs.com/package/ngx-socket-io

**Comment by jimisjames** [comment]
any solution to this?

**Comment by christian-quisbert** [comment]
No, but use this library that solve the problem : [ngx-socket-io](https://www.npmjs.com/package/ngx-socket-io)
`npm i ngx-socket-io`
